<x-layouts.admin :title="$post->exists ? 'Edit Post' : 'Create Post'">
    <form method="POST" action="{{ $post->exists ? route('admin.posts.update', $post) : route('admin.posts.store') }}" enctype="multipart/form-data" class="grid gap-6 xl:grid-cols-[1fr_22rem]">@csrf @if($post->exists) @method('PUT') @endif
        <div class="card p-6">
            <div class="grid gap-4 sm:grid-cols-2"><div><label class="label">Title</label><input name="title" data-slug-source="#post-slug" value="{{ old('title', $post->title) }}" class="input" required></div><div><label class="label">Slug</label><input id="post-slug" name="slug" value="{{ old('slug', $post->slug) }}" class="input" required></div></div>
            <div class="mt-4"><label class="label">Excerpt</label><textarea name="excerpt" rows="3" class="input" required>{{ old('excerpt', $post->excerpt) }}</textarea></div>
            <div class="mt-4"><label class="label">Content</label><div class="mb-2 flex flex-wrap gap-2"><button type="button" class="btn-ghost" data-command="bold">B</button><button type="button" class="btn-ghost" data-command="italic">I</button><button type="button" class="btn-ghost" data-command="formatBlock" data-value="h2">H2</button><button type="button" class="btn-ghost" data-command="insertUnorderedList">List</button><button type="button" class="btn-ghost" data-command="formatBlock" data-value="blockquote">Quote</button></div><div data-editor="#post-content" contenteditable="true" class="article-content min-h-72 rounded-lg border border-slate-200 bg-white p-4 focus:outline-none focus:ring-4 focus:ring-teal-100">{!! old('content', $post->content) !!}</div><textarea id="post-content" name="content" class="hidden">{{ old('content', $post->content) }}</textarea></div>
            <div class="mt-4 grid gap-4 sm:grid-cols-2"><div><label class="label">Meta Title</label><input name="meta_title" value="{{ old('meta_title', $post->meta_title) }}" class="input"></div><div><label class="label">Meta Description</label><input name="meta_description" value="{{ old('meta_description', $post->meta_description) }}" class="input"></div></div>
        </div>
        <aside class="space-y-6">
            <div class="card p-5"><label class="label">Category</label><select name="category_id" class="input" required><option value="">Choose category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $post->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select><label class="label mt-4">Tags</label><div class="grid max-h-48 gap-2 overflow-auto rounded-lg border border-slate-200 p-3">@foreach($tags as $tag)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="tags[]" value="{{ $tag->id }}" @checked(in_array($tag->id, old('tags', $selectedTags)))> {{ $tag->name }}</label>@endforeach</div></div>
            <div class="card p-5"><label class="label">Status</label><select name="status" class="input"><option value="draft" @selected(old('status', $post->status) === 'draft')>Draft</option><option value="published" @selected(old('status', $post->status) === 'published')>Published</option></select><label class="mt-4 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $post->is_featured))> Featured</label><label class="label mt-4">Publication Date</label><input name="published_at" type="datetime-local" value="{{ old('published_at', optional($post->published_at)->format('Y-m-d\TH:i')) }}" class="input"></div>
            <div class="card p-5"><label class="label">Featured Image</label>@if($post->featured_image)<img src="{{ $post->featured_image_url }}" alt="{{ $post->title }}" class="mb-3 h-40 w-full rounded-lg object-cover">@endif<input name="featured_image" type="file" accept="image/*" class="input"></div>
            <div class="flex gap-3"><button class="btn-primary">Save Post</button><a href="{{ route('admin.posts.index') }}" class="btn-ghost">Cancel</a></div>
        </aside>
    </form>
</x-layouts.admin>
